title: Darker Ink
description: Personal blog of Felipe Erias
author: Felipe Erias
url: "https://darker.ink"
email: felipeerias@gmail.com
twitter_username: felipeerias
github_username:  felipeerias

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed

permalink: /writings/:title
